export const EMAILS = [
  {
    id: 1,
    from: "john@doe.com",
    title: "Welcome to the club",
    content: "Hello, welcome to the club",
    status: "draft",
  },
  {
    id: 2,
    from: "jane@doe.com",
    title: "Meeting Reminder",
    content: "Don't forget about the meeting tomorrow.",
    status: "sent",
  },
  {
    id: 3,
    from: "admin@website.com",
    title: "Account Activation",
    content: "Please activate your account using the link below.",
    status: "sent",
  },
  {
    id: 4,
    from: "newsletter@company.com",
    title: "Monthly Newsletter",
    content: "Here is our monthly newsletter.",
    status: "active",
  },
  {
    id: 5,
    from: "support@service.com",
    title: "Support Ticket Update",
    content: "Your support ticket has been updated.",
    status: "draft",
  },
  {
    id: 6,
    from: "info@business.com",
    title: "Business Proposal",
    content: "We would like to discuss a business proposal with you.",
    status: "sent",
  },
  {
    id: 7,
    from: "alerts@system.com",
    title: "System Alert",
    content: "There is a new alert in the system.",
    status: "active",
  },
  {
    id: 8,
    from: "events@community.com",
    title: "Community Event",
    content: "Join us for the upcoming community event.",
    status: "draft",
  },
  {
    id: 9,
    from: "offers@shop.com",
    title: "Special Offer",
    content: "Check out our special offer for this month.",
    status: "active",
  },
  {
    id: 10,
    from: "reminder@service.com",
    title: "Payment Reminder",
    content: "This is a reminder for your upcoming payment.",
    status: "active",
  },
  {
    id: 11,
    from: "news@daily.com",
    title: "Daily News",
    content: "Here is your daily news update.",
    status: "sent",
  },
  {
    id: 12,
    from: "promo@deals.com",
    title: "Exclusive Deals",
    content: "Don't miss out on these exclusive deals.",
    status: "active",
  },
  {
    id: 13,
    from: "updates@service.com",
    title: "Service Updates",
    content: "We have some updates to our service.",
    status: "draft",
  },
  {
    id: 14,
    from: "info@conference.com",
    title: "Conference Invitation",
    content: "You are invited to our annual conference.",
    status: "sent",
  },
  {
    id: 15,
    from: "alerts@security.com",
    title: "Security Alert",
    content: "There is a new security alert.",
    status: "active",
  },
  {
    id: 16,
    from: "info@webinar.com",
    title: "Webinar Invitation",
    content: "Join our upcoming webinar.",
    status: "sent",
  },
  {
    id: 17,
    from: "noreply@service.com",
    title: "Password Reset",
    content: "Click the link below to reset your password.",
    status: "draft",
  },
  {
    id: 18,
    from: "contact@company.com",
    title: "Contact Us",
    content: "Feel free to contact us for more information.",
    status: "active",
  },
  {
    id: 19,
    from: "info@newsletter.com",
    title: "Weekly Newsletter",
    content: "Here is your weekly newsletter.",
    status: "sent",
  },
  {
    id: 20,
    from: "support@helpdesk.com",
    title: "Helpdesk Ticket",
    content: "Your helpdesk ticket has been received.",
    status: "active",
  },
  {
    id: 21,
    from: "info@updates.com",
    title: "Important Update",
    content: "Please read this important update.",
    status: "sent",
  },
  {
    id: 22,
    from: "newsletter@weekly.com",
    title: "Weekly Digest",
    content: "Here is your weekly digest.",
    status: "active",
  },
  {
    id: 23,
    from: "alerts@notifications.com",
    title: "Notification Alert",
    content: "You have a new notification.",
    status: "draft",
  },
  {
    id: 24,
    from: "events@calendar.com",
    title: "Event Reminder",
    content: "Don't forget about the upcoming event.",
    status: "sent",
  },
  {
    id: 25,
    from: "offers@discounts.com",
    title: "Discount Offer",
    content: "Enjoy a special discount on your next purchase.",
    status: "active",
  },
  {
    id: 26,
    from: "info@updates.com",
    title: "System Update",
    content: "We have updated our system.",
    status: "draft",
  },
  {
    id: 27,
    from: "news@daily.com",
    title: "Daily Briefing",
    content: "Here is your daily briefing.",
    status: "sent",
  },
  {
    id: 28,
    from: "promo@deals.com",
    title: "Limited Time Offer",
    content: "Don't miss this limited time offer.",
    status: "active",
  },
  {
    id: 29,
    from: "info@conference.com",
    title: "Conference Details",
    content: "Here are the details for the upcoming conference.",
    status: "draft",
  },
  {
    id: 30,
    from: "alerts@security.com",
    title: "Security Notice",
    content: "Please review this important security notice.",
    status: "sent",
  },
  {
    id: 31,
    from: "info@updates.com",
    title: "New Features",
    content: "Check out the new features in our latest update.",
    status: "active",
  },
  {
    id: 32,
    from: "newsletter@monthly.com",
    title: "Monthly Recap",
    content: "Here is a recap of this month's highlights.",
    status: "sent",
  },
  {
    id: 33,
    from: "alerts@system.com",
    title: "System Downtime",
    content: "Scheduled system downtime will occur this weekend.",
    status: "draft",
  },
  {
    id: 34,
    from: "events@community.com",
    title: "Community Gathering",
    content: "Join us for a community gathering next week.",
    status: "active",
  },
  {
    id: 35,
    from: "offers@shop.com",
    title: "Flash Sale",
    content: "Don't miss our flash sale this weekend.",
    status: "sent",
  },
  {
    id: 36,
    from: "info@updates.com",
    title: "Service Interruption",
    content: "We are experiencing a temporary service interruption.",
    status: "draft",
  },
  {
    id: 37,
    from: "news@daily.com",
    title: "Morning Brief",
    content: "Here is your morning brief.",
    status: "active",
  },
  {
    id: 38,
    from: "promo@deals.com",
    title: "Holiday Sale",
    content: "Enjoy our holiday sale with great discounts.",
    status: "sent",
  },
  {
    id: 39,
    from: "info@conference.com",
    title: "Conference Agenda",
    content: "Here is the agenda for the upcoming conference.",
    status: "draft",
  },
  {
    id: 40,
    from: "alerts@security.com",
    title: "Security Update",
    content: "Please review the latest security update.",
    status: "active",
  },
  {
    id: 41,
    from: "info@updates.com",
    title: "Feature Announcement",
    content: "We are excited to announce a new feature.",
    status: "sent",
  },
  {
    id: 42,
    from: "newsletter@monthly.com",
    title: "Monthly Highlights",
    content: "Here are the highlights for this month.",
    status: "active",
  },
  {
    id: 43,
    from: "alerts@system.com",
    title: "System Maintenance",
    content: "Scheduled maintenance will occur this weekend.",
    status: "draft",
  },
  {
    id: 44,
    from: "events@community.com",
    title: "Community Meetup",
    content: "Join us for a community meetup next month.",
    status: "sent",
  },
  {
    id: 45,
    from: "offers@shop.com",
    title: "Weekend Sale",
    content: "Don't miss our weekend sale.",
    status: "active",
  },
  {
    id: 46,
    from: "info@updates.com",
    title: "Service Downtime",
    content: "We are experiencing a temporary service downtime.",
    status: "draft",
  },
  {
    id: 47,
    from: "news@daily.com",
    title: "Evening Brief",
    content: "Here is your evening brief.",
    status: "sent",
  },
  {
    id: 48,
    from: "promo@deals.com",
    title: "Black Friday Sale",
    content: "Enjoy our Black Friday sale with huge discounts.",
    status: "active",
  },
  {
    id: 49,
    from: "info@conference.com",
    title: "Conference Speakers",
    content: "Here is the list of speakers for the upcoming conference.",
    status: "draft",
  },
  {
    id: 50,
    from: "alerts@security.com",
    title: "Security Patch",
    content: "Please apply the latest security patch.",
    status: "sent",
  },
];
